version: '3'
services:
  postgresql:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project2
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - item-network
  server:
    build: .
    ports:
      - '8080:8080'
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/project2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    depends_on:
      - postgresql
    networks:
      - item-network
networks:
  item-network:
volumes:
  postgresql-data: